Table view dynamic cells
Cona7/ZeplinTask pull request #1
Opened 2018-11-02 15:30 UTC by Cona7

2018-11-03 12:04 UTC, Rep2 requested changes

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        let number: String = "8545"
`: String` nije potreban

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +    let arrayTotal: [CellModel] = [CellModel(name: "Total workouts"),
`: [CellModel]` nije potreban.

Za array je bolje staviti element u novi red ako ima vise od 1 element

```
[
    CellModel(name: "Total workouts"),
    CellModel(name: "Total reps")
]
```

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        menuBtn.setImage(UIImage(named: pictureString), for: .normal)
Zamjeni `UIImage(named: )` s `Image Literal`. To je noviji i "compile safe" nacin dodavanja slika.

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        let currWidth = settingsBarItem.customView?.widthAnchor.constraint(equalToConstant: 22.3)
Fix image (1, 2, 3x).

Remove constraints and frame from BarButton.

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        self.navigationItem.rightBarButtonItem = settingsBarItem
Remove `self.`

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +    override func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
Func not needed.

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        if section == 0 {
`return section == 0 ? arrayTotal.count  : arrayMuscles.count` is better for this use case IMO

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +        cell.numberLabel.textColor = .customBlue
Can the text font and color be set in IB?

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditProfileViewController.swift
> +        if let keyboardSize = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
Can the 2 ifs be combined?

2018-11-03 12:04 UTC, Rep2 commented on ZeplinTask/EditProfileViewController.swift
> +                self.view.layoutIfNeeded()
Unneeded `self.`

2018-11-04 17:03 UTC, Cona7 commented on ZeplinTask/EditViewController.swift
> +        cell.numberLabel.textColor = .customBlue
Yes, I will correct this. Font and color can be set in IB, but my UILabel letter spacing extension does not work well in IB as well as it works in code. So, probably, that is the reason why I left font and color setter in code.

2018-11-05 08:53 UTC, Rep2 requested changes

2018-11-05 08:53 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +                        CellModel(name: "Total workouts"),
@Cona7 Wrong indentation

2018-11-05 08:53 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +    let pictureString = "Image-1"
Think this is unused

2018-11-05 13:23 UTC, Cona7 commented on ZeplinTask/EditViewController.swift
> +                        CellModel(name: "Total workouts"),
Here's your example you mentioned above:

```
[
    CellModel(name: "Total workouts"),
    CellModel(name: "Total reps")
]
```
I missed one space, but i still don't understand,
do I need to achieve it like this:
```
let arrayMuscles =
    [
        CellModel(name: "Triceps"),
        CellModel(name: "Biceps"),
        CellModel(name: "Bench")
    ]
```

2018-11-05 13:32 UTC, Rep2 commented on ZeplinTask/EditViewController.swift
> +                        CellModel(name: "Total workouts"),
Like this:

```Swift
    let arrayMuscles = [
        CellModel(name: "Triceps"),
        CellModel(name: "Biceps"),
        CellModel(name: "Bench")
    ]
```

Your indentation was like this

```Swift
    let arrayMuscles = [
                          CellModel(name: "Triceps"),
                          CellModel(name: "Biceps"),
                          CellModel(name: "Bench")
                       ]
```

2018-11-06 15:56 UTC, Rep2 approved these changes

2018-11-06 16:11 UTC, merged